/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Pannello */

#ifndef _Included_Pannello
#define _Included_Pannello
#ifdef __cplusplus
extern "C" {
#endif
#undef Pannello_FOCUS_TRAVERSABLE_UNKNOWN
#define Pannello_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef Pannello_FOCUS_TRAVERSABLE_DEFAULT
#define Pannello_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef Pannello_FOCUS_TRAVERSABLE_SET
#define Pannello_FOCUS_TRAVERSABLE_SET 2L
#undef Pannello_TOP_ALIGNMENT
#define Pannello_TOP_ALIGNMENT 0.0f
#undef Pannello_CENTER_ALIGNMENT
#define Pannello_CENTER_ALIGNMENT 0.5f
#undef Pannello_BOTTOM_ALIGNMENT
#define Pannello_BOTTOM_ALIGNMENT 1.0f
#undef Pannello_LEFT_ALIGNMENT
#define Pannello_LEFT_ALIGNMENT 0.0f
#undef Pannello_RIGHT_ALIGNMENT
#define Pannello_RIGHT_ALIGNMENT 1.0f
#undef Pannello_serialVersionUID
#define Pannello_serialVersionUID -7644114512714619750LL
#undef Pannello_serialVersionUID
#define Pannello_serialVersionUID 4613797578919906343LL
#undef Pannello_INCLUDE_SELF
#define Pannello_INCLUDE_SELF 1L
#undef Pannello_SEARCH_HEAVYWEIGHTS
#define Pannello_SEARCH_HEAVYWEIGHTS 1L
#undef Pannello_NOT_OBSCURED
#define Pannello_NOT_OBSCURED 0L
#undef Pannello_PARTIALLY_OBSCURED
#define Pannello_PARTIALLY_OBSCURED 1L
#undef Pannello_COMPLETELY_OBSCURED
#define Pannello_COMPLETELY_OBSCURED 2L
#undef Pannello_WHEN_FOCUSED
#define Pannello_WHEN_FOCUSED 0L
#undef Pannello_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT
#define Pannello_WHEN_ANCESTOR_OF_FOCUSED_COMPONENT 1L
#undef Pannello_WHEN_IN_FOCUSED_WINDOW
#define Pannello_WHEN_IN_FOCUSED_WINDOW 2L
#undef Pannello_UNDEFINED_CONDITION
#define Pannello_UNDEFINED_CONDITION -1L
#undef Pannello_IS_DOUBLE_BUFFERED
#define Pannello_IS_DOUBLE_BUFFERED 0L
#undef Pannello_ANCESTOR_USING_BUFFER
#define Pannello_ANCESTOR_USING_BUFFER 1L
#undef Pannello_IS_PAINTING_TILE
#define Pannello_IS_PAINTING_TILE 2L
#undef Pannello_IS_OPAQUE
#define Pannello_IS_OPAQUE 3L
#undef Pannello_KEY_EVENTS_ENABLED
#define Pannello_KEY_EVENTS_ENABLED 4L
#undef Pannello_FOCUS_INPUTMAP_CREATED
#define Pannello_FOCUS_INPUTMAP_CREATED 5L
#undef Pannello_ANCESTOR_INPUTMAP_CREATED
#define Pannello_ANCESTOR_INPUTMAP_CREATED 6L
#undef Pannello_WIF_INPUTMAP_CREATED
#define Pannello_WIF_INPUTMAP_CREATED 7L
#undef Pannello_ACTIONMAP_CREATED
#define Pannello_ACTIONMAP_CREATED 8L
#undef Pannello_CREATED_DOUBLE_BUFFER
#define Pannello_CREATED_DOUBLE_BUFFER 9L
#undef Pannello_IS_PRINTING
#define Pannello_IS_PRINTING 11L
#undef Pannello_IS_PRINTING_ALL
#define Pannello_IS_PRINTING_ALL 12L
#undef Pannello_IS_REPAINTING
#define Pannello_IS_REPAINTING 13L
#undef Pannello_WRITE_OBJ_COUNTER_FIRST
#define Pannello_WRITE_OBJ_COUNTER_FIRST 14L
#undef Pannello_RESERVED_1
#define Pannello_RESERVED_1 15L
#undef Pannello_RESERVED_2
#define Pannello_RESERVED_2 16L
#undef Pannello_RESERVED_3
#define Pannello_RESERVED_3 17L
#undef Pannello_RESERVED_4
#define Pannello_RESERVED_4 18L
#undef Pannello_RESERVED_5
#define Pannello_RESERVED_5 19L
#undef Pannello_RESERVED_6
#define Pannello_RESERVED_6 20L
#undef Pannello_WRITE_OBJ_COUNTER_LAST
#define Pannello_WRITE_OBJ_COUNTER_LAST 21L
#undef Pannello_REQUEST_FOCUS_DISABLED
#define Pannello_REQUEST_FOCUS_DISABLED 22L
#undef Pannello_INHERITS_POPUP_MENU
#define Pannello_INHERITS_POPUP_MENU 23L
#undef Pannello_OPAQUE_SET
#define Pannello_OPAQUE_SET 24L
#undef Pannello_AUTOSCROLLS_SET
#define Pannello_AUTOSCROLLS_SET 25L
#undef Pannello_FOCUS_TRAVERSAL_KEYS_FORWARD_SET
#define Pannello_FOCUS_TRAVERSAL_KEYS_FORWARD_SET 26L
#undef Pannello_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET
#define Pannello_FOCUS_TRAVERSAL_KEYS_BACKWARD_SET 27L
/*
 * Class:     Pannello
 * Method:    apriSeriale
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Pannello_apriSeriale
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Pannello
 * Method:    leggiDaSeriale
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Pannello_leggiDaSeriale
  (JNIEnv *, jclass);

/*
 * Class:     Pannello
 * Method:    prendiValoreLetto
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Pannello_prendiValoreLetto
  (JNIEnv *, jclass, jint);

/*
 * Class:     Pannello
 * Method:    chiudiSeriale
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Pannello_chiudiSeriale
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
